services:
  homedash:
    image: fuguone/homedash:latest
    container_name: homedash
    ports:
      - "8080:8080"
    volumes:
      - /path/to/your/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /path/to/your/homedash/config.yaml:/etc/config/config.yaml:ro
    restart: unless-stopped
    environment:
      - PORT=8080
